const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Cache,patch,strip,atomic,BEGIN,END}=require('../src/cache.cjs');const {defaults,css}=require('../src/profile.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'quickcss-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const cacheRoot=path.join(root,'cache');fs.mkdirSync(cacheRoot);const cache=new Cache(cacheRoot,path.join(root,'state'));const base='body { --font-text-size:16px; } .markdown-rendered{}\n';
 function generation(id){const dir=path.join(cacheRoot,id.repeat(64));fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'quicklook.css'),base);fs.writeFileSync(path.join(dir,'index.html'),'<link href="quicklook.css"><script src="quicklook.js"></script>');fs.writeFileSync(path.join(dir,'quicklook.js'),'onQuickLookReady');const current=path.join(cacheRoot,'current');if(fs.existsSync(current))fs.unlinkSync(current);fs.symlinkSync(dir,current);return path.join(dir,'quicklook.css');}return {cache,base,generation};}
test('patch is idempotent and exact restoration preserves leading/trailing unrelated edits',()=>{const base='original\n';const value=patch(base,'body{}');assert.equal(patch(value,'body{}'),value);assert.equal(strip(value),base);assert.equal(strip('prefix'+value+'suffix'),'prefix'+base+'suffix');});
test('malformed, unknown and duplicate markers fail closed',()=>{for(const v of [BEGIN+'x',END+'x','/* quickcss:begin v2 */',patch('', 'x')+patch('','y')])assert.throws(()=>strip(v));});
test('apply retains original backup, makes no repeated CSS writes, preserves foreign edits on restore',t=>{const {cache,base,generation}=fixture(t),file=generation('a');cache.apply(defaults,'vault A','1.14.4');const mtime=fs.statSync(file).mtimeMs;assert.equal(cache.reconcile().changed,false);assert.equal(fs.statSync(file).mtimeMs,mtime);fs.appendFileSync(file,'\n/* foreign change */');assert.equal(cache.restore(),1);assert.equal(fs.readFileSync(file,'utf8'),base+'\n/* foreign change */');assert.equal(cache.state().enabled,false);const backups=fs.readdirSync(path.join(cache.stateRoot,'backups'));assert.equal(fs.readFileSync(path.join(cache.stateRoot,'backups',backups[0]),'utf8'),base);});
test('a second vault reconciles shared profile; replacements receive selected CSS',t=>{const {cache,generation}=fixture(t);generation('a');cache.apply({...defaults,size:25},'vault A','1.14.4');const other=new Cache(cache.root,cache.stateRoot);const file=generation('b');assert.equal(other.reconcile().changed,true);assert.match(fs.readFileSync(file,'utf8'),/25px/);assert.equal(other.state().label,'vault A');assert.equal(other.restore(),2);});
test('unsupported renderer is refused without profile activation',t=>{const {cache,generation}=fixture(t);const file=generation('a');fs.writeFileSync(path.join(path.dirname(file),'index.html'),'new renderer');assert.throws(()=>cache.apply(defaults,'A','2'));assert.equal(cache.state().enabled,false);});
test('external symlink and resource symlink are rejected',t=>{const {cache,generation}=fixture(t);const file=generation('a');fs.unlinkSync(file);fs.symlinkSync(cache.stateRoot,file);assert.throws(()=>cache.current());});
test('concurrent lock blocks writes and leaves selected state intact',t=>{const {cache,generation}=fixture(t);generation('a');cache.apply(defaults,'A','1');fs.writeFileSync(path.join(cache.stateRoot,'write.lock'),'another');assert.throws(()=>cache.apply({...defaults,size:30},'B','1'));assert.equal(cache.state().label,'A');});
test('compare before atomic write protects against intervening changes',t=>{const {generation}=fixture(t),file=generation('a');assert.throws(()=>atomic(file,'replacement','old'));assert.match(fs.readFileSync(file,'utf8'),/font-text-size/);});
test('restore stops auto reapply even when a corrupted block prevents removal',t=>{const {cache,generation}=fixture(t),file=generation('a');cache.apply(defaults,'A','1');fs.appendFileSync(file,BEGIN);assert.throws(()=>cache.restore());assert.equal(cache.state().enabled,false);assert.equal(cache.reconcile().enabled,false);});
test('profile constraints reject invalid values, imports and marker injection',()=>{for(const p of [{size:NaN},{size:100},{font:'x;}'},{accent:'red'},{customCss:'@import "https://example.com";'},{customCss:'/* quickcss:end */'}])assert.throws(()=>css({...defaults,...p}));assert.match(css(defaults),/theme-dark/);});
