const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const ROOT=require('node:os').tmpdir(),{Cache,BEGIN}=require('../src/cache.cjs');
const snapshot={schema:2,css:'body.theme-light{color:black}\nbody.theme-dark{color:white}',theme:'Synthetic',snippets:[],styleSettings:false};
function setup(t){
 const root=fs.mkdtempSync(path.join(ROOT,'lifecycle-')),cacheRoot=path.join(root,'cache'),dir=path.join(cacheRoot,'a'.repeat(64));fs.mkdirSync(dir,{recursive:true});fs.symlinkSync(dir,path.join(cacheRoot,'current'));const file=path.join(dir,'quicklook.css'),base='body{--font-text-size:16px}.markdown-rendered{}';fs.writeFileSync(file,base);fs.writeFileSync(path.join(dir,'index.html'),'<link href="quicklook.css"><script src="quicklook.js"></script>');fs.writeFileSync(path.join(dir,'quicklook.js'),'onQuickLookReady');
 const original=Module._load,previous={document:global.document,window:global.window,MutationObserver:global.MutationObserver};let disconnects=0,clears=0,tabs=[],ticks=[],events={},observers=[];
 global.document={head:{},body:{classList:['theme-dark'],style:{cssText:''}},documentElement:{className:'',style:{cssText:''}},styleSheets:[],adoptedStyleSheets:[]};global.window={setInterval:fn=>{ticks.push(fn);return 1;},clearInterval:()=>clears++};global.MutationObserver=class{constructor(fn){observers.push(fn);}observe(){}disconnect(){disconnects++;}};
 class Plugin{async loadData(){return this.saved||null;}async saveData(data){this.saved=data;}registerEvent(){}register(fn){this.cleanup=fn;}addCommand(){}addSettingTab(tab){tabs.push(tab);}}
 Module._load=function(id,...args){if(id==='obsidian')return {Plugin,PluginSettingTab:class{constructor(app,plugin){this.app=app;this.plugin=plugin;}},Notice:class{},Platform:{isMacOS:true},apiVersion:'1.14.4'};if(id==='./cache.cjs')return {...require('../src/cache.cjs'),Cache:class extends Cache{constructor(){super(cacheRoot,path.join(root,'state'));}}};return original.call(this,id,...args);};delete require.cache[require.resolve('../src/main.js')];const QuickCss=require('../src/main.js');Module._load=original;
 function instance(name,saved){const p=new QuickCss();p.saved=saved;p.app={vault:{adapter:{getBasePath:()=>path.join(root,name),read:async()=>'{"cssTheme":"Synthetic"}'},configDir:'.obsidian',getName:()=>name},workspace:{on(name,fn){events[name]=fn;return {};},onLayoutReady(fn){p.layout=fn;}}};return p;}
 t.after(()=>{for(const tab of tabs)tab.plugin.onunload();global.document=previous.document;global.window=previous.window;global.MutationObserver=previous.MutationObserver;fs.rmSync(root,{recursive:true,force:true});});return {instance,file,base,root,ticks,events,observers,counts:()=>({disconnects,clears})};
}
test('load, manual sync, pause, normal quit and paused restart retain state; source disable restores',async t=>{const {instance,file,base,counts}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();a.captureCurrent=async()=>snapshot;await a.syncNow();assert.match(fs.readFileSync(file,'utf8'),/color:white/);await a.setAutomatic(false);assert.equal(a.saved.autoSync,false);const bytes=fs.readFileSync(file,'utf8');a.beginShutdown();a.onunload();assert.equal(fs.readFileSync(file,'utf8'),bytes);assert.deepEqual(counts(),{disconnects:4,clears:2});const restarted=instance('A',a.saved);await restarted.onload();restarted.layout();assert.equal(restarted.autoSync,false);assert.equal(restarted.sync.timer,null);assert.equal(restarted.snapshot.theme,'Synthetic');assert.equal(fs.readFileSync(file,'utf8'),bytes);restarted.onunload();assert.equal(fs.readFileSync(file,'utf8'),base);assert.equal(restarted.cache.state().enabled,false);});
test('follower restart and disable preserve owner; explicit takeover transfers cleanup responsibility',async t=>{const {instance,file,base}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();a.captureCurrent=async()=>snapshot;await a.syncNow();const b=instance('B');await b.onload();b.layout();assert.equal(b.owns(),false);assert.equal(b.sync.timer,null);const bytes=fs.readFileSync(file,'utf8');b.onunload();assert.equal(fs.readFileSync(file,'utf8'),bytes);const b2=instance('B');await b2.onload();b2.layout();b2.captureCurrent=async()=>({...snapshot,theme:'B'});await b2.syncNow();assert.equal(b2.owns(),true);assert.equal(a.owns(),false);a.onunload();assert.ok(fs.readFileSync(file,'utf8').includes(BEGIN));b2.onunload();assert.equal(fs.readFileSync(file,'utf8'),base);});
test('restore and pause persists across restarted plugin and cannot reapply automatically',async t=>{const {instance,file,base}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();a.captureCurrent=async()=>snapshot;await a.syncNow();await a.restore();assert.equal(a.saved.autoSync,false);assert.equal(fs.readFileSync(file,'utf8'),base);a.beginShutdown();a.onunload();const restarted=instance('A',a.saved);await restarted.onload();restarted.layout();restarted.poll();await restarted.sync.run();assert.equal(restarted.autoSync,false);assert.equal(restarted.cache.state().enabled,false);assert.equal(fs.readFileSync(file,'utf8'),base);});
test('automatic toggle pending settings save cannot claim or schedule after shutdown',async t=>{const {instance}=setup(t),a=instance('A');await a.onload();a.autoSync=false;let resolve;a.saveData=()=>new Promise(r=>resolve=r);let claims=0,schedules=0;a.cache.claim=()=>claims++;a.sync.schedule=()=>schedules++;const pending=a.setAutomatic(true);a.beginShutdown();resolve();await pending;assert.equal(claims,0,'claim after quit');assert.equal(schedules,0,'schedule after quit');});
test('restore pending settings save cannot remove appearance after ordinary quit',async t=>{const {instance,file}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();a.captureCurrent=async()=>snapshot;await a.syncNow();const bytes=fs.readFileSync(file,'utf8');let resolve;a.saveData=()=>new Promise(r=>resolve=r);const pending=a.restore();a.beginShutdown();a.onunload();resolve();await pending;assert.equal(fs.readFileSync(file,'utf8'),bytes,'restore after quit changes CSS');assert.equal(a.cache.state().enabled,true);});
test('restore invalidates an in-flight manual sync so it cannot repaint restored CSS',async t=>{const {instance,file,base}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();let resolve;a.captureCurrent=()=>new Promise(r=>resolve=r);const pending=a.syncNow();await a.restore();resolve(snapshot);await pending;assert.equal(fs.readFileSync(file,'utf8'),base);assert.equal(a.cache.state().enabled,false);assert.equal(a.autoSync,false);});
test('manual sync while paused completes even while an old automatic capture is pending',async t=>{const {instance,file}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();let resolve,captures=0;a.captureCurrent=()=>++captures===1?new Promise(r=>resolve=r):Promise.resolve(snapshot);const automatic=a.sync.run();assert.equal(a.sync.running,true);await a.setAutomatic(false);await a.syncNow();assert.equal(captures,2);assert.match(fs.readFileSync(file,'utf8'),/color:white/);resolve({...snapshot,css:'body{color:red}'});await automatic;assert.ok(!fs.readFileSync(file,'utf8').includes('color:red'));assert.equal(a.autoSync,false);});

test('cache timer never scans stylesheets or schedules captures; appearance events still schedule',async t=>{const {instance,ticks,events,observers}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();let schedules=0,polls=0;a.sync.schedule=()=>schedules++;a.poll=()=>polls++;Object.defineProperty(global.document,'styleSheets',{get(){throw Error('idle stylesheet scan');},configurable:true});ticks[0]();assert.equal(polls,1);assert.equal(schedules,0);events['css-change']();assert.equal(schedules,1);observers[0]([{target:{matches:()=>true},addedNodes:[],removedNodes:[]}]);assert.equal(schedules,2);global.document.body.classList=['theme-light'];observers[1]();assert.equal(schedules,3);global.document.body.classList=['theme-light','is-focused'];observers[1]();assert.equal(schedules,3);a.beginShutdown();ticks[0]();events['css-change']();assert.equal(polls,1);assert.equal(schedules,3);});

test('appearance change deferred during manual sync is captured after manual sync finishes',async t=>{const {instance,file}=setup(t),a=instance('A');await a.onload();a.layout();a.sync.cancel();a.sync.options.delay=5;let resolve,captures=0;const newer={...snapshot,css:'body.theme-dark{color:purple}'};a.captureCurrent=()=>++captures===1?new Promise(r=>resolve=r):Promise.resolve(newer);const manual=a.syncNow();a.scheduleAppearance();await new Promise(r=>setTimeout(r,25));assert.equal(captures,1);assert.equal(a.sync.pending,true);assert.equal(a.sync.timer,null);resolve(snapshot);await manual;await new Promise(r=>setTimeout(r,25));assert.equal(captures,2);assert.match(fs.readFileSync(file,'utf8'),/color:purple/);});
